name: Backend-ci

on:
  push:
    branches: [main]
    paths: ["backend/**"]
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ["backend/**"]

jobs:
  git-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove deploy label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "deploy: backend"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      - name: Install deps
        run: npm install
        working-directory: "backend"

      - name: Run ci
        run: npm ci
        working-directory: "backend"

  # docker-push:
  #   needs: git-ci
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: print location
  #       run: pwd

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./backend
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/nft-mkp-api:latest

  # deploy-aws:
  #   needs: deploy-git
  #   runs-on: aws-nft

  #   steps:
  #     - name: stop old image
  #       run: sudo docker-compose stop
  #     - name: remove old image
  #       run: sudo docker-compose rm -f
  #     - name: pull new image
  #       run: sudo docker-compose pull
  #     - name: run new image
  #       run: sudo docker-compose up -d
  #     - name: prune images
  #       run: sudo docker image prune -af
