name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["backend", "frontend", "smart_contract"] }

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install deps
        run: npm install
        working-directory: ${{ matrix.dir }}

      - name: Run build
        run: npm run lint && npm run build
        working-directory: ${{ matrix.dir }}
