name: Production

on:
  pull_request:
    types: [labeled]

jobs:
  deploy-backend:
    if: "${{ github.event.label.name == 'prod: backend' }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove deploy label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "prod: backend"

      - name: Deploy to EC2 instance
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          # Command execution location
          working-directory: /home/ubuntu
          command: |
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -af
          comment: docker-compose.yml file re-pulls newer versions of images and runs them on the instance.
