name: Staging

on:
  pull_request:
    types: [labeled]

jobs: 
  deploy-backend:
    if: "${{ github.event.label.name == 'deploy: backend' }}"
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Remove deploy label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "deploy: backend"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nft-mkp-api:latest
